// src/flash-issues/formatter.ts
// Formats the flash-issues Markdown snapshot and console summary report.

import type { ClassifiedResult, FlashIssuesReconciliation, RepoScanResult } from "./types.ts";

export function formatMarkdown(
  classified: ClassifiedResult,
  now: Date = new Date(),
): string {
  const header = [
    "# Flash-lane issues",
    "",
    "_Regenerated by /flash-issues — do not hand-edit, next run replaces this file._",
    "",
    `Last updated: ${now.toISOString()}`,
  ].join("\n");

  const sections: string[] = [header];

  // Section 1: Fix your open PRs first
  if (classified.fixPrs.length > 0) {
    const lines: string[] = ["## Fix your open PRs first", ""];
    for (const item of classified.fixPrs) {
      const milestoneClause = item.milestone ? `, milestone: ${item.milestone}` : "";
      if (item.reviewState === "changes_requested") {
        const count = item.mustFixCount || 1;
        const reviewUrl = item.reviewUrl || item.prUrl;
        lines.push(
          `- [${item.repo}#${item.number}](${item.url}) — ${item.title} (${item.tier}${milestoneClause}) — PR: [${item.repo}#${item.prNumber}](${item.prUrl}) (\`${item.headRefName}\`) — changes requested: ${count} must fix — [review](${reviewUrl})`,
        );
      } else {
        lines.push(
          `- [${item.repo}#${item.number}](${item.url}) — ${item.title} (${item.tier}${milestoneClause}) — PR: [${item.repo}#${item.prNumber}](${item.prUrl}) (\`${item.headRefName}\`) — CI failing — [review](${item.prUrl})`,
        );
      }
    }
    sections.push(lines.join("\n"));
  }

  // Section 2: Numbered runnable list
  if (classified.runnable.length > 0) {
    const lines: string[] = [];
    classified.runnable.forEach((item, idx) => {
      const num = idx + 1;
      const milestoneClause = item.milestone ? `, milestone: ${item.milestone}` : "";
      const depClause = item.samePoolDependency
        ? `, depends on ${item.samePoolDependency.repo}#${item.samePoolDependency.number} above`
        : "";
      lines.push(
        `${num}. [${item.repo}#${item.number}](${item.url}) — ${item.title} (${item.tier}${milestoneClause}${depClause})`,
      );
    });
    sections.push(lines.join("\n"));
  }

  // Section 3: In Flight (Pending PR Review)
  if (classified.inFlight.length > 0) {
    const lines: string[] = ["## In Flight (Pending PR Review)", ""];
    for (const item of classified.inFlight) {
      const milestoneClause = item.milestone ? `, milestone: ${item.milestone}` : "";
      if (item.reviewState === "approved") {
        lines.push(
          `- [${item.repo}#${item.number}](${item.url}) — ${item.title} (${item.tier}${milestoneClause}) — PR: [${item.repo}#${item.prNumber}](${item.prUrl}) (\`${item.headRefName}\`) — reviewed — approved`,
        );
      } else {
        lines.push(
          `- [${item.repo}#${item.number}](${item.url}) — ${item.title} (${item.tier}${milestoneClause}) — PR: [${item.repo}#${item.prNumber}](${item.prUrl}) (\`${item.headRefName}\`)`,
        );
      }
    }
    sections.push(lines.join("\n"));
  }

  // Section 4: Blocked (not runnable by Flash)
  if (classified.blocked.length > 0) {
    const lines: string[] = ["## Blocked (not runnable by Flash)", ""];
    for (const item of classified.blocked) {
      const milestoneClause = item.milestone ? `, milestone: ${item.milestone}` : "";
      const cleanReason = item.blockedReason.replace(/^blocked:\s*/i, "");
      lines.push(
        `- [${item.repo}#${item.number}](${item.url}) — ${item.title} (${item.tier}${milestoneClause}) — blocked: ${cleanReason}`,
      );
    }
    sections.push(lines.join("\n"));
  }

  // Section 5: Needs Josh's review
  if (classified.needsReview.length > 0) {
    const lines: string[] = [
      "## Needs Josh's review (no agent will touch these until you decide)",
      "",
    ];
    for (const item of classified.needsReview) {
      lines.push(
        `- [${item.repo}#${item.number}](${item.url}) — ${item.title} — ${item.recommendation}`,
      );
    }
    sections.push(lines.join("\n"));
  }

  return sections.join("\n\n") + "\n";
}

export function formatConsoleReport(
  reconciliation: FlashIssuesReconciliation,
  classified: ClassifiedResult,
  scanResults: RepoScanResult[],
  outputPath: string,
): string {
  const lines: string[] = [
    "## Flash-lane worklist regeneration complete",
    "",
    "### Repos scanned",
  ];

  for (const scan of scanResults) {
    lines.push(
      `- **${scan.repo}**: ${scan.issues.length} open issues, ${scan.prs.length} open PRs (${scan.labels.length} labels)`,
    );
  }

  lines.push("");
  lines.push(`### Newly labeled issues: ${classified.newlyLabeled.length}`);
  if (classified.newlyLabeled.length === 0) {
    lines.push("None");
  } else {
    for (const l of classified.newlyLabeled) {
      lines.push(`- ${l.repo}#${l.number} → \`${l.label}\``);
    }
  }

  lines.push("");
  lines.push("### Bucket breakdown");
  lines.push(
    `- **Fix your open PRs first**: ${reconciliation.bucketCounts.fixPrs.total} (${reconciliation.bucketCounts.fixPrs.changesRequested} changes requested, ${reconciliation.bucketCounts.fixPrs.ciFailing} CI failing)`,
  );
  lines.push(`- **Numbered runnable list**: ${reconciliation.bucketCounts.runnable}`);
  lines.push(
    `- **In Flight (Pending PR Review)**: ${reconciliation.bucketCounts.inFlight.total} (${reconciliation.bucketCounts.inFlight.unreviewed} unreviewed, ${reconciliation.bucketCounts.inFlight.approved} approved)`,
  );
  lines.push(`- **Blocked (not runnable by Flash)**: ${reconciliation.bucketCounts.blocked}`);
  lines.push(
    `- **Needs Josh's review**: ${reconciliation.bucketCounts.needsReview}`,
  );
  lines.push(
    `- **Skipped (other model label)**: ${reconciliation.bucketCounts.skippedOtherModel}`,
  );
  lines.push(
    `- **Skipped (parked / Josh)**: ${reconciliation.bucketCounts.skippedParkedJosh}`,
  );

  lines.push("");
  lines.push("### Step 8 Reconciliation");
  if (reconciliation.reconciled) {
    lines.push(
      `✅ Verified exact match: ${reconciliation.totalScanned} scanned == ${reconciliation.totalCategorized} categorized.`,
    );
  } else {
    lines.push(
      `❌ RECONCILIATION MISMATCH: ${reconciliation.totalScanned} scanned != ${reconciliation.totalCategorized} categorized!`,
    );
  }

  lines.push("");
  lines.push("### Confirmations");
  lines.push(
    "- Priority, Type, and dependencies read from native REST payloads (`gh api repos/WebJamApps/<repo>/issues/<n>`).",
  );
  lines.push("- Topics resolved from Milestones.");
  lines.push("- Open PRs evaluated with CI and automated review statuses.");
  lines.push(`- Output snapshot written to: ${outputPath}`);

  return lines.join("\n") + "\n";
}
