// src/book-gig/gmail.ts — Gmail draft creation and run logging for /book-gig

import type { BookGigResult, PitchEmail } from "./types.ts";
import { renderDarkHtml } from "./html.ts";

export interface CreateDraftResult {
  venueId: string;
  venueName: string;
  to: string;
  subject: string;
  draftCreated: boolean;
  draftId?: string;
  error?: string;
}

/**
 * Format a pitch as a Gmail draft object (ready for Gmail API or MCP)
 */
export function formatDraftPayload(pitch: PitchEmail): {
  to: string;
  cc?: string;
  subject: string;
  body: string;
} {
  return {
    to: pitch.to,
    cc: pitch.secondaryTo,
    subject: pitch.subject,
    body: pitch.body,
  };
}

/**
 * Record an outreach run log in Dropbox for Josh's records (Markdown + Responsive Dark Mode HTML)
 */
export async function writeDropboxRunLog(
  result: BookGigResult,
  outputDir = `${Deno.env.get("HOME")}/Dropbox/web-jam-llms/gig-outreach`,
): Promise<string | null> {
  try {
    await Deno.mkdir(outputDir, { recursive: true });
    const dateSlug = result.weekend
      ? `${result.weekend.start}-to-${result.weekend.end}`
      : `replies-${new Date().toISOString().slice(0, 10)}`;
    const mdPath = `${outputDir}/book-gig-run-${dateSlug}.md`;
    const htmlPath = `${outputDir}/book-gig-run-${dateSlug}.html`;

    const candidateRows = result.candidates.map((c, i) =>
      `| ${i + 1} | ${c.name} | ${c.city || "—"}, ${c.usState || "—"} | ${c.email || "—"} | ${
        c.reason?.spacingNote || "—"
      } |`
    ).join("\n");

    const pitchBlocks = result.pitches.map((p, i) =>
      `### Pitch ${i + 1}: ${p.venueName}
- **To:** \`${p.to}\`${p.secondaryTo ? ` (CC: \`${p.secondaryTo}\`)` : ""}
- **Subject:** ${p.subject}

\`\`\`text
${p.body}
\`\`\`
`
    ).join("\n\n");

    const weekendHeader = result.weekend
      ? `${result.weekend.start} to ${result.weekend.end} (${result.weekend.label})`
      : "All Active Outreach Campaigns";

    let dispatchSummary = "";
    if (result.batchDispatch) {
      dispatchSummary =
        `\n**Batch Dispatch:** ${result.batchDispatch.sent} sent / ${result.batchDispatch.requested} requested (${result.batchDispatch.skipped.length} skipped)  `;
    }

    let repliesSummary = "";
    if (result.repliesTracking) {
      repliesSummary =
        `\n**Replies Scan:** ${result.repliesTracking.checkReplies.checked} checked, ${result.repliesTracking.checkReplies.matched} matched (${result.repliesTracking.pendingReplies.length} pending review)  `;
    }

    const content = `# \`book-gig\` Run Record: ${result.weekend?.label || "Outreach Status"}

**Run Timestamp:** ${new Date().toISOString()}  
**Mode:** ${result.mode}  
**Target Weekend:** ${weekendHeader}  
**Target Location Filter:** ${
      result.location ? result.location.raw : "All Regional Metros (~3.5h drive)"
    }  
**Candidates Found:** ${result.candidates.length} (Sparse: ${
      result.density.isSparse ? "Yes" : "No"
    })  
**Pitches Drafted:** ${result.pitches.length}  ${dispatchSummary}${repliesSummary}

---

## 1. Candidate Venues Evaluated

| # | Venue Name | Location | Booking Email | Spacing Note |
|---|---|---|---|---|
${candidateRows || "| — | No candidates found | — | — | — |"}

---

## 2. Generated Gmail Pitches

${pitchBlocks || "*No pitches generated.*"}

---

*Note: Generated by WebJamApps \`book-gig\` outreach pipeline.*
`;

    await Deno.writeTextFile(mdPath, content);

    // Generate and write standalone responsive Dark Mode HTML for Chrome review
    const htmlContent = renderDarkHtml(result);
    await Deno.writeTextFile(htmlPath, htmlContent);

    return mdPath;
  } catch (err) {
    console.warn(`[book-gig] Failed to write run log to Dropbox: ${(err as Error).message}`);
    return null;
  }
}
